import React, { useState, useMemo, useEffect, useCallback } from 'react';
import Tile from './Tile';
import AlgorithmInfo from './AlgorithmInfo';
import { DIFFICULTY_LEVELS, DIRECTION_ROTATION } from '../utils/constants';
import { getNextClockwiseDirection, formatTime, calculatePathCost } from '../utils/helpers';
import { generateSolvableGrid, generateDailyGrid } from '../utils/boardGenerator';
import { calculateFlowPath } from '../algorithms/pathfinding';
import { solveBFS } from '../algorithms/bfs';
import { solveDFS } from '../algorithms/dfs';
import { solveDijkstra } from '../algorithms/dijkstra';
import { MousePointerClick, RotateCcw, AlertCircle, Trophy, RefreshCw, Footprints, Timer, Dices, Award, Zap, GitBranch, Calendar, Cpu, Settings, ChevronDown } from 'lucide-react';
import '../css/GameBoard.css';

/**
 * Reusable GameBoard component managing matrix state, three DAA game modes (BFS, DFS, Dijkstra),
 * path evaluation, win detection, centered statistics, live move tracking, and locked START tile.
 */
export default function GameBoard({
  difficultyKey = 'MEDIUM',
  isDailyMode = false,
  dailyDateStr,
  initialDailyGrid,
  onDailyComplete,
  selectedAlgoMode = 'BFS',
  showAlgorithmInfo = false,
  isTimerEnabled = true,
  isAnimationsEnabled = true,
  isSoundEnabled = true,
  onMoveCountChange,
  onGameStatusChange,
  onElapsedTimeChange,
  onDifficultyChange,
  onOpenSettings,
  onRegisterControls,
}) {
  // Selected active graph algorithm ('BFS', 'DFS', or 'DIJKSTRA')
  const [activeAlgorithm, setActiveAlgorithm] = useState(selectedAlgoMode);
  // Controls win completion modal visibility overlay
  const [showWinModal, setShowWinModal] = useState(false);

  // Sync activeAlgorithm when selectedAlgoMode prop changes
  useEffect(() => {
    if (selectedAlgoMode) {
      setActiveAlgorithm(selectedAlgoMode);
    }
  }, [selectedAlgoMode]);

  // Active difficulty configuration
  const diffConfig = DIFFICULTY_LEVELS[difficultyKey] || DIFFICULTY_LEVELS.MEDIUM;

  // Store active board tiles generated by puzzle generator
  const [grid, setGrid] = useState(() => {
    if (isDailyMode && initialDailyGrid) return initialDailyGrid;
    return generateSolvableGrid(diffConfig.rows, diffConfig.cols, difficultyKey, activeAlgorithm);
  });

  // Regenerate grid when difficultyKey or activeAlgorithm prop changes (non-daily)
  useEffect(() => {
    if (!isDailyMode) {
      const targetConfig = DIFFICULTY_LEVELS[difficultyKey] || DIFFICULTY_LEVELS.MEDIUM;
      const newBoard = generateSolvableGrid(targetConfig.rows, targetConfig.cols, difficultyKey, activeAlgorithm);
      setGrid(newBoard);
      setInitialGrid(newBoard);
      setMoveCount(0);
      setElapsedSeconds(0);
      setShowWinModal(false);
    }
  }, [difficultyKey, activeAlgorithm, isDailyMode]);

  // Store initial layout of current puzzle for Reset Board & Play Again actions
  const [initialGrid, setInitialGrid] = useState(grid);
  // Move counter state
  const [moveCount, setMoveCount] = useState(0);
  // Elapsed time state in seconds
  const [elapsedSeconds, setElapsedSeconds] = useState(0);

  /**
   * Recalculate player's actual flow path traversal whenever grid state changes.
   */
  const flowResult = useMemo(() => {
    return calculateFlowPath(grid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, diffConfig]);

  /**
   * Execute Breadth-First Search (BFS) algorithm.
   */
  const bfsResult = useMemo(() => {
    return solveBFS(grid, initialGrid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, initialGrid, diffConfig]);

  /**
   * Execute Depth-First Search (DFS) algorithm.
   */
  const dfsResult = useMemo(() => {
    return solveDFS(grid, initialGrid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, initialGrid, diffConfig]);

  /**
   * Execute Dijkstra's Shortest Path algorithm for weighted movement costs.
   */
  const dijkstraResult = useMemo(() => {
    return solveDijkstra(grid, initialGrid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, initialGrid, diffConfig]);

  // Active algorithm result depending on user selection
  const algoResult =
    activeAlgorithm === 'BFS'
      ? bfsResult
      : activeAlgorithm === 'DFS'
      ? dfsResult
      : dijkstraResult;

  const isWon = flowResult.reachedTarget;
  const playerSteps = flowResult.path.length > 0 ? flowResult.path.length - 1 : 0;
  const playerTotalMoves = moveCount + playerSteps;

  // Calculate player's live path cost accumulated along their current path prefix
  const playerPathCost = useMemo(() => {
    return calculatePathCost(grid, flowResult.path);
  }, [grid, flowResult.path]);

  // Trigger win modal on solve
  useEffect(() => {
    if (isWon) {
      setShowWinModal(true);
      if (isDailyMode && onDailyComplete) {
        onDailyComplete({
          moves: playerTotalMoves,
          time: elapsedSeconds,
          cost: playerPathCost,
        });
      }
    }
  }, [isWon, isDailyMode, playerTotalMoves, elapsedSeconds, playerPathCost, onDailyComplete]);

  // Zero-dependency Timer Effect: Ticks every second while timer is enabled and puzzle is active
  useEffect(() => {
    let interval = null;

    if (isTimerEnabled && !isWon) {
      interval = setInterval(() => {
        setElapsedSeconds((prev) => prev + 1);
      }, 1000);
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerEnabled, isWon]);

  // Sync parent component callbacks if provided
  useEffect(() => {
    if (onMoveCountChange) onMoveCountChange(playerTotalMoves);
    if (onGameStatusChange) onGameStatusChange(isWon ? 'SOLVED' : 'IDLE');
    if (onElapsedTimeChange) onElapsedTimeChange(elapsedSeconds);
    if (onDifficultyChange) onDifficultyChange(diffConfig.label);
  }, [playerTotalMoves, isWon, elapsedSeconds, diffConfig, onMoveCountChange, onGameStatusChange, onElapsedTimeChange, onDifficultyChange]);

  /**
   * Generates a brand new solvable puzzle grid for the given difficulty and resets counters.
   */
  const handleNewPuzzle = useCallback((targetDifficultyKey = difficultyKey) => {
    if (isDailyMode) {
      const dailyGrid = generateDailyGrid(dailyDateStr);
      setGrid(dailyGrid);
      setInitialGrid(dailyGrid);
    } else {
      const targetConfig = DIFFICULTY_LEVELS[targetDifficultyKey] || DIFFICULTY_LEVELS.MEDIUM;
      const newBoard = generateSolvableGrid(targetConfig.rows, targetConfig.cols, targetDifficultyKey, activeAlgorithm);
      setGrid(newBoard);
      setInitialGrid(newBoard);
    }
    setMoveCount(0);
    setElapsedSeconds(0);
    setShowWinModal(false);
  }, [difficultyKey, isDailyMode, dailyDateStr, activeAlgorithm]);

  /**
   * Click handler to rotate arrow clockwise (+90°) ONLY on regular tiles.
   * START and TARGET tiles are locked and cannot be rotated.
   * Reactively increments move counter on every valid rotation.
   */
  const handleTileClick = (row, col) => {
    if (isWon) return;

    const clickedTile = grid[row]?.[col];
    // Ignore click on START or TARGET tiles — START direction is fixed by problem setup
    if (!clickedTile || clickedTile.isStart || clickedTile.isTarget) return;

    setGrid((prevGrid) =>
      prevGrid.map((r, rIdx) =>
        r.map((tile, cIdx) => {
          if (rIdx === row && cIdx === col) {
            const nextArrow = getNextClockwiseDirection(tile.arrow);
            const nextDegrees = DIRECTION_ROTATION[nextArrow] !== undefined
              ? DIRECTION_ROTATION[nextArrow]
              : 0;

            return {
              ...tile,
              arrow: nextArrow,
              rotationDegrees: nextDegrees,
            };
          }
          return tile;
        })
      )
    );

    // Increment UI move counter reactively on every valid tile rotation
    setMoveCount((prev) => prev + 1);
  };

  /**
   * Resets current board back to its initial layout and resets move counter + timer.
   */
  const handleResetCurrentBoard = useCallback(() => {
    setGrid(initialGrid);
    setMoveCount(0);
    setElapsedSeconds(0);
    setShowWinModal(false);
  }, [initialGrid]);

  // Register header game control functions with parent single navbar
  useEffect(() => {
    if (onRegisterControls) {
      onRegisterControls({
        newGame: () => handleNewPuzzle(difficultyKey),
        reset: handleResetCurrentBoard,
      });
    }
  }, [onRegisterControls, handleNewPuzzle, handleResetCurrentBoard, difficultyKey]);

  // Check if player's path achieves true optimal score for current mode across full board
  const isPerfect =
    activeAlgorithm === 'DIJKSTRA'
      ? playerPathCost === dijkstraResult.optimalBoardCost
      : activeAlgorithm === 'BFS'
      ? playerTotalMoves === bfsResult.optimalBoardMoves
      : activeAlgorithm === 'DFS'
      ? playerPathCost === dfsResult.optimalBoardCost && playerTotalMoves === dfsResult.optimalBoardMoves
      : false;

  return (
    <div className="game-layout-container">
      {/* 3-Column Grid Layout: Left Stats | Center Board | Right Explanation */}
      <div className="game-3col-layout">
        {/* Left Column: Live Game Stats */}
        <aside className="game-left-panel">
          <div className="side-stats-card">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <h3 className="side-card-title">{isDailyMode ? 'Daily Challenge' : `${diffConfig.label} Mode`}</h3>
              <span className="board-badge">{diffConfig.rows} × {diffConfig.cols}</span>
            </div>

            <div className="side-stats-grid">
              <div className="stat-pill-box">
                <Footprints size={16} style={{ color: 'var(--accent-cyan)' }} />
                <div>
                  <span className="stat-pill-label">Moves</span>
                  <span className="stat-pill-val">{playerTotalMoves}</span>
                </div>
              </div>

              {(activeAlgorithm === 'DIJKSTRA' || activeAlgorithm === 'DFS') && (
                <div className="stat-pill-box">
                  <Award size={16} style={{ color: '#c084fc' }} />
                  <div>
                    <span className="stat-pill-label">Path Cost</span>
                    <span className="stat-pill-val" style={{ color: '#c084fc' }}>{playerPathCost}</span>
                  </div>
                </div>
              )}

              {isTimerEnabled && (
                <div className="stat-pill-box">
                  <Timer size={16} style={{ color: 'var(--accent-indigo)' }} />
                  <div>
                    <span className="stat-pill-label">Time</span>
                    <span className="stat-pill-val">{formatTime(elapsedSeconds)}</span>
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="side-hint-box">
            <MousePointerClick size={16} style={{ color: 'var(--accent-cyan)', flexShrink: 0 }} />
            <span>Click arrow tiles to configure the path from Start to Goal.</span>
          </div>
        </aside>

        {/* Center Column: Prominent Centered Game Board Canvas */}
        <main className="game-center-panel">
          <div className="flow-status-bar">
            {flowResult.stopReason === 'LOOP' ? (
              <div className="status-pill status-warning">
                <AlertCircle size={15} />
                <span>Loop Detected (Cost: {playerPathCost})</span>
              </div>
            ) : flowResult.stopReason === 'OUT_OF_BOUNDS' ? (
              <div className="status-pill status-muted">
                <span>Path Left Board ({playerTotalMoves} Moves | Cost: {playerPathCost})</span>
              </div>
            ) : (
              <div className="status-pill status-info">
                {activeAlgorithm === 'DIJKSTRA' || activeAlgorithm === 'DFS' ? (
                  <span>Path Steps: {playerSteps} | Moves: <strong>{playerTotalMoves}</strong> | Path Cost: <strong>{playerPathCost}</strong></span>
                ) : (
                  <span>Path Steps: {playerSteps} | Moves: <strong>{playerTotalMoves}</strong></span>
                )}
              </div>
            )}
          </div>

          {/* Dynamic Responsive Grid Canvas */}
          <div
            className="grid-5x5-canvas"
            style={{
              '--grid-cols': diffConfig.cols,
              '--grid-rows': diffConfig.rows,
            }}
          >
            {grid.map((row) =>
              row.map((tile) => {
                const tileKey = `${tile.row}-${tile.col}`;
                const tileIndex = flowResult.path.findIndex(
                  (p) => p.row === tile.row && p.col === tile.col
                );
                const inPath = tileIndex !== -1;
                const isNextTile =
                  inPath &&
                  !flowResult.reachedTarget &&
                  tileIndex === flowResult.path.length - 1 &&
                  !tile.isStart &&
                  !tile.isTarget;
                const isVisited =
                  inPath &&
                  (flowResult.reachedTarget || tileIndex < flowResult.path.length - 1) &&
                  !tile.isTarget;

                return (
                  <Tile
                    key={tileKey}
                    tile={tile}
                    isReachable={inPath}
                    isVisited={isVisited}
                    isNextTile={isNextTile}
                    onTileClick={handleTileClick}
                  />
                );
              })
            )}
          </div>

          {/* Developer Algorithm Info section when enabled */}
          {showAlgorithmInfo && (
            <AlgorithmInfo
              algoResult={algoResult}
              activeAlgorithm={activeAlgorithm}
              onSelectAlgorithm={setActiveAlgorithm}
            />
          )}
        </main>

        {/* Right Column: Algorithm Description Card */}
        <aside className="game-right-panel">
          <div className="algo-explain-card">
            <div className={`algo-explain-header ${activeAlgorithm.toLowerCase()}`}>
              {activeAlgorithm === 'DIJKSTRA' ? (
                <Award size={20} style={{ color: '#c084fc' }} />
              ) : activeAlgorithm === 'DFS' ? (
                <GitBranch size={20} style={{ color: '#818cf8' }} />
              ) : (
                <Zap size={20} style={{ color: 'var(--accent-cyan)' }} />
              )}
              <div>
                <h3 className="algo-explain-title">
                  {activeAlgorithm === 'DIJKSTRA'
                    ? 'Dijkstra Mode'
                    : activeAlgorithm === 'DFS'
                    ? 'Perfect Route Mode'
                    : 'BFS Mode'}
                </h3>
                <span className={`algo-tag-badge ${activeAlgorithm.toLowerCase()}`}>
                  {activeAlgorithm === 'DIJKSTRA'
                    ? '💎 Min Path Cost'
                    : activeAlgorithm === 'DFS'
                    ? '⭐ Min Cost & Moves'
                    : '⚡ Min Moves'}
                </span>
              </div>
            </div>

            <div className="algo-explain-body">
              <p className="explain-text-enhanced">
                {activeAlgorithm === 'DIJKSTRA'
                  ? 'Finds the path from Start to Goal with the minimum total path cost across tile entry values.'
                  : activeAlgorithm === 'DFS'
                  ? 'Finds the ultimate optimal route by calculating both minimum path cost and minimum move count.'
                  : 'Finds the shortest path requiring the fewest total moves (tile rotations + steps) to reach the Goal.'}
              </p>
            </div>
          </div>
        </aside>
      </div>

      {/* Front-Center Completion Modal Overlay */}
      {isWon && showWinModal && (
        <div className="completion-modal-overlay">
          <div className="completion-modal-card">
            <div className="completion-icon">
              {isPerfect ? <Award size={28} /> : <Trophy size={26} />}
            </div>

            <h3 className="completion-title">
              {isDailyMode ? 'Daily Challenge Complete!' : 'Flow Complete!'}
              {activeAlgorithm === 'DIJKSTRA' ? (
                isPerfect ? (
                  <span style={{ color: '#facc15', marginLeft: '6px' }}> ⭐ Perfect Cost!</span>
                ) : (
                  <span style={{ color: '#38bdf8', fontSize: '0.85rem', marginLeft: '6px' }}> (Suboptimal Cost)</span>
                )
              ) : activeAlgorithm === 'BFS' ? (
                isPerfect ? (
                  <span style={{ color: '#facc15', marginLeft: '6px' }}> ⭐ Perfect Moves!</span>
                ) : (
                  <span style={{ color: '#38bdf8', fontSize: '0.85rem', marginLeft: '6px' }}> (Path Connected)</span>
                )
              ) : (
                isPerfect ? (
                  <span style={{ color: '#facc15', marginLeft: '6px' }}> ⭐ Perfect Route!</span>
                ) : (
                  <span style={{ color: '#38bdf8', fontSize: '0.85rem', marginLeft: '6px' }}> (Route Connected)</span>
                )
              )}
            </h3>

            <p className="completion-sub">
              {activeAlgorithm === 'DIJKSTRA' ? (
                <>
                  Your Path Cost: <strong>{playerPathCost}</strong> | Minimum Board Cost: <strong>{dijkstraResult.optimalBoardCost}</strong>
                  {!isPerfect && (
                    <span className="opt-warning-hint">
                      💡 A lower-cost path (Cost: {dijkstraResult.optimalBoardCost}) is possible on this board! Click "Play Again" to retry this exact board.
                    </span>
                  )}
                </>
              ) : activeAlgorithm === 'BFS' ? (
                <>
                  Your Total Moves: <strong>{playerTotalMoves}</strong> | Minimum Board Moves: <strong>{bfsResult.optimalBoardMoves}</strong>
                  {!isPerfect && (
                    <span className="opt-warning-hint">
                      💡 A path requiring fewer total moves ({bfsResult.optimalBoardMoves} moves) is possible on this board! Click "Play Again" to retry.
                    </span>
                  )}
                </>
              ) : (
                <>
                  Your Path Cost: <strong>{playerPathCost}</strong> (Optimum: <strong>{dfsResult.optimalBoardCost}</strong>) | Total Moves: <strong>{playerTotalMoves}</strong> (Optimum: <strong>{dfsResult.optimalBoardMoves}</strong>)
                  {!isPerfect && (
                    <span className="opt-warning-hint">
                      💡 A better route (Cost: {dfsResult.optimalBoardCost}, Moves: {dfsResult.optimalBoardMoves}) is possible on this board! Click "Play Again" to retry.
                    </span>
                  )}
                </>
              )}
            </p>

            <div className="modal-actions-row">
              <button className="btn-modal-action secondary" onClick={handleResetCurrentBoard} title="Retry exact same board">
                <RotateCcw size={16} />
                <span>Play Again</span>
              </button>

              {!isDailyMode && (
                <button className="btn-modal-action primary" onClick={() => handleNewPuzzle(difficultyKey)} title="Generate brand new board">
                  <Dices size={16} />
                  <span>New Game</span>
                </button>
              )}

              <button className="btn-modal-text" onClick={() => setShowWinModal(false)}>
                View Solved Board
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
