import React, { useState, useMemo, useEffect, useCallback } from 'react';
import Tile from './Tile';
import { GRID_ROWS, GRID_COLS } from '../utils/constants';
import { getNextClockwiseDirection, formatTime } from '../utils/helpers';
import { generateSolvableGrid } from '../utils/boardGenerator';
import { calculateFlowPath } from '../algorithms/pathfinding';
import { MousePointerClick, RotateCcw, AlertCircle, Trophy, RefreshCw, Footprints, Timer, Dices } from 'lucide-react';
import '../css/GameBoard.css';

/**
 * Reusable GameBoard component managing matrix state, path traversal, win detection, move counting, timer, and puzzle generation.
 */
export default function GameBoard({
  isTimerEnabled = true,
  onMoveCountChange,
  onGameStatusChange,
  onElapsedTimeChange,
  onRegisterNewPuzzleHandler,
}) {
  // Store active board tiles generated by puzzle generator
  const [grid, setGrid] = useState(() => generateSolvableGrid(GRID_ROWS, GRID_COLS));
  // Store initial layout of current puzzle for Reset Board action
  const [initialGrid, setInitialGrid] = useState(grid);
  // Simple move counter state
  const [moveCount, setMoveCount] = useState(0);
  // Elapsed time state in seconds
  const [elapsedSeconds, setElapsedSeconds] = useState(0);

  /**
   * Recalculate path traversal whenever grid state changes.
   * Win detection occurs when flowResult.reachedTarget is true.
   */
  const flowResult = useMemo(() => {
    return calculateFlowPath(grid);
  }, [grid]);

  const isWon = flowResult.reachedTarget;

  // Zero-dependency Timer Effect: Ticks every second while timer is enabled and puzzle is active
  useEffect(() => {
    let interval = null;

    if (isTimerEnabled && !isWon) {
      interval = setInterval(() => {
        setElapsedSeconds((prev) => prev + 1);
      }, 1000);
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerEnabled, isWon]);

  // Sync parent component callbacks if provided
  useEffect(() => {
    if (onMoveCountChange) onMoveCountChange(moveCount);
    if (onGameStatusChange) onGameStatusChange(isWon ? 'SOLVED' : 'IDLE');
    if (onElapsedTimeChange) onElapsedTimeChange(elapsedSeconds);
  }, [moveCount, isWon, elapsedSeconds, onMoveCountChange, onGameStatusChange, onElapsedTimeChange]);

  /**
   * Generates a brand new solvable puzzle grid and resets counters.
   */
  const handleNewPuzzle = useCallback(() => {
    const newBoard = generateSolvableGrid(GRID_ROWS, GRID_COLS);
    setGrid(newBoard);
    setInitialGrid(newBoard);
    setMoveCount(0);
    setElapsedSeconds(0);
  }, []);

  // Register New Puzzle handler to parent if needed
  useEffect(() => {
    if (onRegisterNewPuzzleHandler) {
      onRegisterNewPuzzleHandler(() => handleNewPuzzle);
    }
  }, [onRegisterNewPuzzleHandler, handleNewPuzzle]);

  /**
   * Click handler to rotate arrow clockwise (+90°) on regular tiles.
   * Increments move counter by 1 on every valid tile rotation.
   */
  const handleTileClick = (row, col) => {
    // Pause board tile interaction once the goal is reached
    if (isWon) return;

    let tileRotated = false;

    setGrid((prevGrid) =>
      prevGrid.map((r, rIdx) =>
        r.map((tile, cIdx) => {
          if (rIdx === row && cIdx === col) {
            // Ignore click on Start or Target tiles
            if (tile.isStart || tile.isTarget) return tile;

            tileRotated = true;

            // Determine next clockwise direction: UP -> RIGHT -> DOWN -> LEFT -> UP
            const nextArrow = getNextClockwiseDirection(tile.arrow);

            // Calculate new rotation angle (+90deg clockwise)
            const nextDegrees = tile.arrow !== null ? tile.rotationDegrees + 90 : 0;

            return {
              ...tile,
              arrow: nextArrow,
              rotationDegrees: nextDegrees,
            };
          }
          return tile;
        })
      )
    );

    // Increment move count if a valid tile was rotated
    if (tileRotated) {
      setMoveCount((prev) => prev + 1);
    }
  };

  /**
   * Resets current board back to its initial layout and resets move counter + timer.
   */
  const handleResetCurrentBoard = () => {
    setGrid(initialGrid);
    setMoveCount(0);
    setElapsedSeconds(0);
  };

  return (
    <div className="game-board-container">
      <div className="board-header">
        <div className="board-title-group">
          <h2 className="board-title">Game Grid</h2>
          <span className="board-badge">{GRID_ROWS} × {GRID_COLS}</span>
        </div>

        {/* Move Counter & Optional Timer Displays at Top of Game */}
        <div className="header-stats-group">
          <div className="move-counter-badge" title="Current Move Count">
            <Footprints size={15} style={{ color: 'var(--accent-cyan)' }} />
            <span>Moves:</span> {moveCount}
          </div>

          {isTimerEnabled && (
            <div className="timer-badge" title="Elapsed Time">
              <Timer size={15} style={{ color: 'var(--accent-indigo)' }} />
              <span>Time:</span> {formatTime(elapsedSeconds)}
            </div>
          )}
        </div>

        <div className="board-actions-group">
          <button className="btn-text-reset" onClick={handleResetCurrentBoard} title="Reset current board state">
            <RotateCcw size={14} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'middle' }} />
            Reset
          </button>
          <button className="btn-text-reset" onClick={handleNewPuzzle} title="Generate new solvable puzzle">
            <Dices size={14} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'middle' }} />
            New
          </button>
        </div>
      </div>

      {/* Completion Banner (Win State) */}
      {isWon ? (
        <div className="completion-card">
          <div className="completion-info">
            <div className="completion-icon">
              <Trophy size={20} />
            </div>
            <div>
              <h3 className="completion-title">Flow Complete!</h3>
              <p className="completion-sub">
                Solved in {moveCount} {moveCount === 1 ? 'move' : 'moves'}
                {isTimerEnabled ? ` (${formatTime(elapsedSeconds)})` : ''}
              </p>
            </div>
          </div>

          {/* Clicking Play Again generates a brand new solvable puzzle board */}
          <button className="btn-play-again" onClick={handleNewPuzzle}>
            <RefreshCw size={15} />
            <span>Play Again</span>
          </button>
        </div>
      ) : (
        /* Status Bar showing live path calculation metrics */
        <div className="flow-status-bar">
          {flowResult.stopReason === 'LOOP' ? (
            <div className="status-pill status-warning">
              <AlertCircle size={15} />
              <span>Loop Detected</span>
            </div>
          ) : flowResult.stopReason === 'OUT_OF_BOUNDS' ? (
            <div className="status-pill status-muted">
              <span>Path Left Board ({flowResult.path.length} Tiles)</span>
            </div>
          ) : (
            <div className="status-pill status-info">
              <span>Path Length: {flowResult.path.length} Tiles</span>
            </div>
          )}
        </div>
      )}

      {/* 5x5 Responsive Grid Canvas */}
      <div className="grid-5x5-canvas">
        {grid.map((row) =>
          row.map((tile) => {
            const tileKey = `${tile.row}-${tile.col}`;
            const isReachable = flowResult.pathSet.has(tileKey);

            return (
              <Tile
                key={tileKey}
                tile={tile}
                isReachable={isReachable}
                onTileClick={handleTileClick}
              />
            );
          })
        )}
      </div>

      <div className="board-hint-bar">
        <div className="hint-text">
          <MousePointerClick size={15} />
          <span>
            {isWon
              ? `Puzzle solved! Click "Play Again" to generate a new board`
              : 'Click any tile to rotate arrow and extend the flow path'}
          </span>
        </div>
      </div>
    </div>
  );
}
