import React, { useState, useMemo, useEffect, useCallback } from 'react';
import Tile from './Tile';
import AlgorithmInfo from './AlgorithmInfo';
import { DIFFICULTY_LEVELS } from '../utils/constants';
import { getNextClockwiseDirection, formatTime, calculatePathCost } from '../utils/helpers';
import { generateSolvableGrid, generateDailyGrid } from '../utils/boardGenerator';
import { calculateFlowPath } from '../algorithms/pathfinding';
import { solveBFS } from '../algorithms/bfs';
import { solveDFS } from '../algorithms/dfs';
import { solveDijkstra } from '../algorithms/dijkstra';
import { MousePointerClick, RotateCcw, AlertCircle, Trophy, RefreshCw, Footprints, Timer, Dices, Award, Zap, GitBranch, Calendar } from 'lucide-react';
import '../css/GameBoard.css';

/**
 * Reusable GameBoard component managing matrix state, path algorithms (BFS, DFS, Dijkstra), weighted costs, win detection, and Daily Mode.
 */
export default function GameBoard({
  isDailyMode = false,
  dailyDateStr,
  initialDailyGrid,
  onDailyComplete,
  selectedAlgoMode = 'BFS',
  showAlgorithmInfo = false,
  isTimerEnabled = true,
  onMoveCountChange,
  onGameStatusChange,
  onElapsedTimeChange,
  onDifficultyChange,
}) {
  // Selected difficulty key state (EASY, MEDIUM, HARD)
  const [difficultyKey, setDifficultyKey] = useState('MEDIUM');
  // Selected active graph algorithm ('BFS', 'DFS', or 'DIJKSTRA')
  const [activeAlgorithm, setActiveAlgorithm] = useState(selectedAlgoMode);

  // Sync activeAlgorithm when selectedAlgoMode prop changes
  useEffect(() => {
    if (selectedAlgoMode) {
      setActiveAlgorithm(selectedAlgoMode);
    }
  }, [selectedAlgoMode]);

  // Active difficulty configuration
  const diffConfig = DIFFICULTY_LEVELS[difficultyKey] || DIFFICULTY_LEVELS.MEDIUM;

  // Store active board tiles generated by puzzle generator
  const [grid, setGrid] = useState(() => {
    if (isDailyMode && initialDailyGrid) return initialDailyGrid;
    return generateSolvableGrid(diffConfig.rows, diffConfig.cols, difficultyKey);
  });

  // Store initial layout of current puzzle for Reset Board action
  const [initialGrid, setInitialGrid] = useState(grid);
  // Move counter state
  const [moveCount, setMoveCount] = useState(0);
  // Elapsed time state in seconds
  const [elapsedSeconds, setElapsedSeconds] = useState(0);

  /**
   * Recalculate basic flow path traversal whenever grid state changes.
   */
  const flowResult = useMemo(() => {
    return calculateFlowPath(grid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, diffConfig]);

  /**
   * Execute Breadth-First Search (BFS) algorithm.
   */
  const bfsResult = useMemo(() => {
    return solveBFS(grid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, diffConfig]);

  /**
   * Execute Depth-First Search (DFS) algorithm.
   */
  const dfsResult = useMemo(() => {
    return solveDFS(grid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, diffConfig]);

  /**
   * Execute Dijkstra's Shortest Path algorithm for weighted movement costs.
   */
  const dijkstraResult = useMemo(() => {
    return solveDijkstra(grid, { row: 0, col: 0 }, { row: diffConfig.rows - 1, col: diffConfig.cols - 1 });
  }, [grid, diffConfig]);

  // Active algorithm result depending on user selection
  const algoResult =
    activeAlgorithm === 'BFS'
      ? bfsResult
      : activeAlgorithm === 'DFS'
      ? dfsResult
      : dijkstraResult;

  const isWon = flowResult.reachedTarget;

  // Calculate player's actual path cost
  const playerPathCost = useMemo(() => {
    return calculatePathCost(grid, flowResult.path);
  }, [grid, flowResult.path]);

  // Save Daily Result when puzzle is solved in Daily Mode
  useEffect(() => {
    if (isWon && isDailyMode && onDailyComplete) {
      onDailyComplete({
        moves: moveCount,
        time: elapsedSeconds,
        cost: playerPathCost,
      });
    }
  }, [isWon, isDailyMode, moveCount, elapsedSeconds, playerPathCost, onDailyComplete]);

  // Zero-dependency Timer Effect: Ticks every second while timer is enabled and puzzle is active
  useEffect(() => {
    let interval = null;

    if (isTimerEnabled && !isWon) {
      interval = setInterval(() => {
        setElapsedSeconds((prev) => prev + 1);
      }, 1000);
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerEnabled, isWon]);

  // Sync parent component callbacks if provided
  useEffect(() => {
    if (onMoveCountChange) onMoveCountChange(moveCount);
    if (onGameStatusChange) onGameStatusChange(isWon ? 'SOLVED' : 'IDLE');
    if (onElapsedTimeChange) onElapsedTimeChange(elapsedSeconds);
    if (onDifficultyChange) onDifficultyChange(diffConfig.label);
  }, [moveCount, isWon, elapsedSeconds, diffConfig, onMoveCountChange, onGameStatusChange, onElapsedTimeChange, onDifficultyChange]);

  /**
   * Generates a brand new solvable puzzle grid for the given difficulty and resets counters.
   */
  const handleNewPuzzle = useCallback((targetDifficultyKey = difficultyKey) => {
    if (isDailyMode) {
      const dailyGrid = generateDailyGrid(dailyDateStr);
      setGrid(dailyGrid);
      setInitialGrid(dailyGrid);
    } else {
      const targetConfig = DIFFICULTY_LEVELS[targetDifficultyKey] || DIFFICULTY_LEVELS.MEDIUM;
      const newBoard = generateSolvableGrid(targetConfig.rows, targetConfig.cols, targetDifficultyKey);
      setGrid(newBoard);
      setInitialGrid(newBoard);
    }
    setMoveCount(0);
    setElapsedSeconds(0);
  }, [difficultyKey, isDailyMode, dailyDateStr]);

  /**
   * Handles difficulty selection switch (Easy, Medium, Hard).
   */
  const handleSelectDifficulty = (key) => {
    if (key === difficultyKey || isDailyMode) return;
    setDifficultyKey(key);
    handleNewPuzzle(key);
  };

  /**
   * Click handler to rotate arrow clockwise (+90°) on regular tiles.
   * Increments move counter by 1 on every valid tile rotation.
   */
  const handleTileClick = (row, col) => {
    // Pause board tile interaction once the goal is reached
    if (isWon) return;

    let tileRotated = false;

    setGrid((prevGrid) =>
      prevGrid.map((r, rIdx) =>
        r.map((tile, cIdx) => {
          if (rIdx === row && cIdx === col) {
            // Ignore click on Start or Target tiles
            if (tile.isStart || tile.isTarget) return tile;

            tileRotated = true;

            // Determine next clockwise direction: UP -> RIGHT -> DOWN -> LEFT -> UP
            const nextArrow = getNextClockwiseDirection(tile.arrow);

            // Calculate new rotation angle (+90deg clockwise)
            const nextDegrees = tile.arrow !== null ? tile.rotationDegrees + 90 : 0;

            return {
              ...tile,
              arrow: nextArrow,
              rotationDegrees: nextDegrees,
            };
          }
          return tile;
        })
      )
    );

    // Increment move count if a valid tile was rotated
    if (tileRotated) {
      setMoveCount((prev) => prev + 1);
    }
  };

  /**
   * Resets current board back to its initial layout and resets move counter + timer.
   */
  const handleResetCurrentBoard = () => {
    setGrid(initialGrid);
    setMoveCount(0);
    setElapsedSeconds(0);
  };

  return (
    <div className="game-board-container">
      <div className="board-header">
        <div className="board-title-group">
          <h2 className="board-title">{isDailyMode ? 'Daily Challenge' : 'Game Grid'}</h2>
          <span className="board-badge">{diffConfig.rows} × {diffConfig.cols}</span>

          {isDailyMode && (
            <span className="board-badge" style={{ backgroundColor: 'rgba(250, 204, 21, 0.15)', color: '#facc15', borderColor: 'rgba(250, 204, 21, 0.3)' }}>
              <Calendar size={13} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'middle' }} />Today
            </span>
          )}
        </div>

        {/* Minimal Difficulty Level Selector Tabs */}
        {!isDailyMode && (
          <div className="difficulty-selector-group" title="Select Difficulty Level">
            {Object.values(DIFFICULTY_LEVELS).map((level) => (
              <button
                key={level.key}
                className={`btn-difficulty ${difficultyKey === level.key ? 'active' : ''}`}
                onClick={() => handleSelectDifficulty(level.key)}
              >
                {level.label}
              </button>
            ))}
          </div>
        )}

        {/* Move Counter & Optional Timer Displays at Top of Game */}
        <div className="header-stats-group">
          <div className="move-counter-badge" title="Current Move Count">
            <Footprints size={15} style={{ color: 'var(--accent-cyan)' }} />
            <span>Moves:</span> {moveCount}
          </div>

          {isTimerEnabled && (
            <div className="timer-badge" title="Elapsed Time">
              <Timer size={15} style={{ color: 'var(--accent-indigo)' }} />
              <span>Time:</span> {formatTime(elapsedSeconds)}
            </div>
          )}
        </div>

        <div className="board-actions-group">
          <button className="btn-text-reset" onClick={handleResetCurrentBoard} title="Reset current board state">
            <RotateCcw size={14} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'middle' }} />
            Reset
          </button>
          {!isDailyMode && (
            <button className="btn-text-reset" onClick={() => handleNewPuzzle(difficultyKey)} title="Generate new solvable puzzle">
              <Dices size={14} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'middle' }} />
              New
            </button>
          )}
        </div>
      </div>

      {/* Completion Banner (Win State) */}
      {isWon ? (
        <div className="completion-card">
          <div className="completion-info">
            <div className="completion-icon">
              {playerPathCost === dijkstraResult.optimalCost ? <Award size={22} /> : <Trophy size={20} />}
            </div>
            <div>
              <h3 className="completion-title">
                {isDailyMode ? 'Daily Challenge Complete!' : 'Flow Complete!'} {playerPathCost === dijkstraResult.optimalCost ? '⭐ Perfect Cost!' : ''}
              </h3>
              <p className="completion-sub">
                Cost: <strong>{playerPathCost}</strong> | Optimal Dijkstra: <strong>{dijkstraResult.optimalCost}</strong>
              </p>
            </div>
          </div>

          <button className="btn-play-again" onClick={() => handleNewPuzzle(difficultyKey)}>
            <RefreshCw size={15} />
            <span>{isDailyMode ? 'Replay' : 'Play Again'}</span>
          </button>
        </div>
      ) : (
        /* Status Bar showing live path calculation & cost metrics */
        <div className="flow-status-bar">
          {flowResult.stopReason === 'LOOP' ? (
            <div className="status-pill status-warning">
              <AlertCircle size={15} />
              <span>Loop Detected</span>
            </div>
          ) : flowResult.stopReason === 'OUT_OF_BOUNDS' ? (
            <div className="status-pill status-muted">
              <span>Path Left Board ({flowResult.path.length} Tiles)</span>
            </div>
          ) : (
            <div className="status-pill status-info">
              <span>Path Length: {flowResult.path.length} Tiles (Cost: {playerPathCost})</span>
            </div>
          )}
        </div>
      )}

      {/* Dynamic Responsive Grid Canvas */}
      <div
        className="grid-5x5-canvas"
        style={{
          '--grid-cols': diffConfig.cols,
          '--grid-rows': diffConfig.rows,
        }}
      >
        {grid.map((row) =>
          row.map((tile) => {
            const tileKey = `${tile.row}-${tile.col}`;
            const isReachable = flowResult.pathSet.has(tileKey);

            return (
              <Tile
                key={tileKey}
                tile={tile}
                isReachable={isReachable}
                onTileClick={handleTileClick}
              />
            );
          })
        )}
      </div>

      <div className="board-hint-bar">
        <div className="hint-text">
          <MousePointerClick size={15} />
          <span>
            {isWon
              ? `Puzzle solved! Cost: ${playerPathCost} (Optimal: ${dijkstraResult.optimalCost})`
              : `${isDailyMode ? 'Today\'s Challenge' : diffConfig.label + ' Mode'}: Rotate tiles to connect Start to Goal`}
          </span>
        </div>
      </div>

      {/* Render Developer Algorithm Information Section when showAlgorithmInfo is true */}
      {showAlgorithmInfo && (
        <AlgorithmInfo
          algoResult={algoResult}
          activeAlgorithm={activeAlgorithm}
          onSelectAlgorithm={setActiveAlgorithm}
        />
      )}
    </div>
  );
}
